### ISSUE TITLE
Crash with ratmogrify 

### ISSUE THREAD

**Issue by TVMC2** [TrashboxBobylev/Rat-King-Adventure#19]
Basically, whenever a rat affected by the Drratedon trait takes damage from any physical attack, the game crashes, here's the log:

***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: motorola
Device: rhode
Model: moto g52
Manufacturer: motorola
Product: rhode_g
SDK: 33
Release: 13

***** APP INFO 
Version: 2.0.0-BETA-5-INDEV
Installed On: 2024-09-09 17:11:41
Updated On: 2024-09-09 17:11:41
Current Date: 2024-09-15 01:59:55

***** ERROR LOG 
java.lang.ClassCastException: com.zrp200.rkpd2.actors.hero.abilities.Ratmogrify$SummonedAlbino cannot be cast to com.zrp200.rkpd2.actors.hero.Hero
	at com.zrp200.rkpd2.actors.buffs.Berserk.maxPower(Berserk.java:255)
	at com.zrp200.rkpd2.actors.buffs.Berserk.damage(Berserk.java:267)
	at com.zrp200.rkpd2.actors.mobs.Rat.defenseProc(Rat.java:102)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:554)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:413)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:409)
	at com.zrp200.rkpd2.actors.mobs.Mob.doAttack(Mob.java:686)
	at com.zrp200.rkpd2.actors.mobs.RipperDemon$Hunting.act(RipperDemon.java:210)
	at com.zrp200.rkpd2.actors.mobs.Mob.act(Mob.java:310)
	at com.zrp200.rkpd2.actors.mobs.RipperDemon.act(RipperDemon.java:119)
	at com.zrp200.rkpd2.actors.Actor.process(Actor.java:283)
	at com.zrp200.rkpd2.scenes.GameScene$2.run(GameScene.java:766)

***** END OF LOG *****

**Comment by AetherSky-arch** [comment]
same issue here on a different device, pasting error log in the hope that itll help find the issue:

***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: Nothing
Device: Pong
Model: A065
Manufacturer: Nothing
Product: PongEEA
SDK: 34
Release: 14

***** APP INFO 
Version: 2.0.1
Installed On: 2024-09-21 13:17:27
Updated On: 2024-10-25 13:23:03
Current Date: 2024-10-31 21:16:26

***** ERROR LOG 
java.lang.ClassCastException: com.zrp200.rkpd2.actors.hero.abilities.Ratmogrify$TransmogRat cannot be cast to com.zrp200.rkpd2.actors.hero.Hero
	at com.zrp200.rkpd2.actors.buffs.Berserk.maxPower(Berserk.java:255)
	at com.zrp200.rkpd2.actors.buffs.Berserk.damage(Berserk.java:267)
	at com.zrp200.rkpd2.actors.hero.abilities.Ratmogrify$TransmogRat.defenseProc(Ratmogrify.java:323)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:556)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:414)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:410)
	at com.zrp200.rkpd2.actors.mobs.Mob.doAttack(Mob.java:686)
	at com.zrp200.rkpd2.actors.mobs.Mob$Hunting.act(Mob.java:1263)
	at com.zrp200.rkpd2.actors.mobs.Mob.act(Mob.java:310)
	at com.zrp200.rkpd2.actors.Actor.process(Actor.java:283)
	at com.zrp200.rkpd2.scenes.GameScene$2.run(GameScene.java:766)



***** END OF LOG *****

**Comment by Huta0c6** [comment]
Me too
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: Redmi
Device: sapphire
Model: 23129RAA4G
Manufacturer: Xiaomi
Product: sapphire_global
SDK: 34
Release: 14

***** APP INFO 
Version: 2.0.2
Installed On: 2024-12-09 22:37:13
Updated On: 2024-12-09 22:37:13
Current Date: 2024-12-16 15:44:06

***** ERROR LOG 
java.lang.ClassCastException: com.zrp200.rkpd2.actors.hero.abilities.Ratmogrify$SummonedRat cannot be cast to com.zrp200.rkpd2.actors.hero.Hero
	at com.zrp200.rkpd2.actors.buffs.Berserk.enchantFactor(Berserk.java:184)
	at com.zrp200.rkpd2.actors.buffs.Berserk.enchantFactor(Berserk.java:189)
	at com.zrp200.rkpd2.items.weapon.Weapon$Enchantment.genericProcChanceMultiplier(Weapon.java:485)
	at com.zrp200.rkpd2.items.weapon.Weapon$Enchantment.genericProcChanceMultiplier(Weapon.java:524)
	at com.zrp200.rkpd2.items.weapon.Weapon$Enchantment.procChanceMultiplier(Weapon.java:528)
	at com.zrp200.rkpd2.items.weapon.enchantments.Vampiric.proc(Vampiric.java:43)
	at com.zrp200.rkpd2.actors.Char.attackProc(Char.java:879)
	at com.zrp200.rkpd2.actors.mobs.Mob.attackProc(Mob.java:821)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:569)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:414)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:410)
	at com.zrp200.rkpd2.actors.mobs.Mob.onAttackComplete(Mob.java:695)
	at com.zrp200.rkpd2.sprites.CharSprite.onComplete(CharSprite.java:916)
	at com.zrp200.rkpd2.sprites.MobSprite.onComplete(MobSprite.java:46)
	at com.watabou.noosa.MovieClip.updateAnimation(MovieClip.java:72)
	at com.watabou.noosa.MovieClip.update(MovieClip.java:49)
	at com.zrp200.rkpd2.sprites.CharSprite.update(CharSprite.java:669)
	at com.zrp200.rkpd2.sprites.MobSprite.update(MobSprite.java:40)
	at com.watabou.noosa.Group.update(Group.java:66)
	at com.watabou.noosa.Group.update(Group.java:66)
	at com.watabou.noosa.Scene.update(Scene.java:63)
	at com.zrp200.rkpd2.scenes.PixelScene.update(PixelScene.java:202)
	at com.zrp200.rkpd2.scenes.GameScene.update(GameScene.java:754)
	at com.watabou.noosa.Game.update(Game.java:285)
	at com.watabou.noosa.Game.step(Game.java:248)
	at com.watabou.noosa.Game.render(Game.java:178)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:505)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)



***** END OF LOG *****
