### ISSUE TITLE
some silly bugs I found

### ISSUE THREAD

**Issue by Lovecutehuy1943** [TrashboxBobylev/Rat-King-Adventure#24]
1/ rat king's rat magic shielding when zapping with a fully charged staff doesnt give any shielding
https://github.com/user-attachments/assets/8fbed086-bd10-462f-a6ac-375e1156534e
2/ the weakling challenge doesnt work with VBALANCED seed (I assume that its already applied so it doesnt work but would be nice if I can make it apply twice for a bit of a challenge)
3/ hostile champions challenge doesnt work with rats in RATRATRAT seed
4/ if you die with an unblessed ankh on ECHECHECH seed, another ech will spawn
- if you let both or more echs die in the same floor, it will only respawn one ech when you enter a diff floor
-- this means as long as only 1 ech dies every floor before you switch floors, you can basically have as many of them as you want (as long as you can get those ankhs ofc)
5/ if you die with unblessed ankh while blocking in COLLOSEUM seed, the game will crash after you revive (dont ask how I found this bug 💀 )
https://github.com/user-attachments/assets/44bd0fea-079b-48d2-aa98-f54b7af1d7f5

crash log for the 5th bug:

***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: KDDI
Device: SCV38
Model: SCV38
Manufacturer: samsung
Product: SCV38_jp_kdi
SDK: 29
Release: 10

***** APP INFO 
Version: 2.0.1
Installed On: 2023-11-22 06:09:55
Updated On: 2024-09-30 23:08:04
Current Date: 2024-10-17 19:15:56

***** ERROR LOG 
java.lang.RuntimeException: fatal error occurred while moving between floors. Seed:1567031403189 depth:5
	at com.zrp200.rkpd2.scenes.InterlevelScene.update(InterlevelScene.java:321)
	at com.watabou.noosa.Game.update(Game.java:285)
	at com.watabou.noosa.Game.step(Game.java:248)
	at com.watabou.noosa.Game.render(Game.java:178)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:505)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.zrp200.rkpd2.sprites.CharSprite.idle()' on a null object reference
	at com.zrp200.rkpd2.actors.buffs.WarriorParry$BlockTrock.detach(WarriorParry.java:89)
	at com.zrp200.rkpd2.actors.hero.Hero.live(Hero.java:695)
	at com.zrp200.rkpd2.actors.hero.Hero.resurrect(Hero.java:3008)
	at com.zrp200.rkpd2.scenes.InterlevelScene.resurrect(InterlevelScene.java:529)
	at com.zrp200.rkpd2.scenes.InterlevelScene.access$700(InterlevelScene.java:59)
	at com.zrp200.rkpd2.scenes.InterlevelScene$3.run(InterlevelScene.java:246)

***** END OF LOG *****

**Comment by Lovecutehuy1943** [comment]
another bug I found:
6/ forbidden runes works very well, it works so well that it reduces the amount of SoU from 15 -> 15
