### ISSUE TITLE
A summoned rat cannot be cast to hero (albino too)

### ISSUE THREAD

**Issue by zayats1** [TrashboxBobylev/Rat-King-Adventure#7]
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: samsung
Device: m13
Model: SM-M135F
Manufacturer: samsung
Product: m13nnxx
SDK: 33
Release: 13

***** APP INFO 
Version: 1.5.1
Installed On: 2023-01-18 20:03:16
Updated On: 2023-01-29 18:29:02
Current Date: 2023-02-04 17:21:10

***** ERROR LOG 
java.lang.ClassCastException: com.zrp200.rkpd2.actors.hero.abilities.Ratmogrify$SummonedRat cannot be cast to com.zrp200.rkpd2.actors.hero.Hero
	at com.zrp200.rkpd2.items.weapon.Weapon$Enchantment.procChanceMultiplier(Weapon.java:408)
	at com.zrp200.rkpd2.items.weapon.enchantments.Explosive.tryProc(Explosive.java:22)
	at com.zrp200.rkpd2.items.weapon.enchantments.Explosive.proc(Explosive.java:26)
	at com.zrp200.rkpd2.actors.Char.attackProc(Char.java:681)
	at com.zrp200.rkpd2.actors.mobs.Mob.attackProc(Mob.java:736)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:431)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:287)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:283)
	at com.zrp200.rkpd2.actors.mobs.Mob.onAttackComplete(Mob.java:630)
	at com.zrp200.rkpd2.sprites.CharSprite.onComplete(CharSprite.java:875)
	at com.zrp200.rkpd2.sprites.MobSprite.onComplete(MobSprite.java:46)
	at com.watabou.noosa.MovieClip.updateAnimation(MovieClip.java:72)
	at com.watabou.noosa.MovieClip.update(MovieClip.java:49)
	at com.zrp200.rkpd2.sprites.CharSprite.update(CharSprite.java:632)
	at com.zrp200.rkpd2.sprites.MobSprite.update(MobSprite.java:40)
	at com.watabou.noosa.Group.update(Group.java:64)
	at com.watabou.noosa.Group.update(Group.java:64)
	at com.watabou.noosa.Scene.update(Scene.java:63)
	at com.zrp200.rkpd2.scenes.PixelScene.update(PixelScene.java:173)
	at com.zrp200.rkpd2.scenes.GameScene.update(GameScene.java:667)
	at com.watabou.noosa.Game.update(Game.java:281)
	at com.watabou.noosa.Game.step(Game.java:245)
	at com.watabou.noosa.Game.render(Game.java:175)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

***** END OF LOG *****
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: samsung
Device: m13
Model: SM-M135F
Manufacturer: samsung
Product: m13nnxx
SDK: 33
Release: 13

***** APP INFO 
Version: 1.5.1
Installed On: 2023-01-18 20:03:16
Updated On: 2023-01-29 18:29:02
Current Date: 2023-02-04 17:21:10

***** ERROR LOG 
java.lang.ClassCastException: com.zrp200.rkpd2.actors.hero.abilities.Ratmogrify$SummonedRat cannot be cast to com.zrp200.rkpd2.actors.hero.Hero
	at com.zrp200.rkpd2.items.weapon.Weapon$Enchantment.procChanceMultiplier(Weapon.java:408)
	at com.zrp200.rkpd2.items.weapon.enchantments.Explosive.tryProc(Explosive.java:22)
	at com.zrp200.rkpd2.items.weapon.enchantments.Explosive.proc(Explosive.java:26)
	at com.zrp200.rkpd2.actors.Char.attackProc(Char.java:681)
	at com.zrp200.rkpd2.actors.mobs.Mob.attackProc(Mob.java:736)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:431)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:287)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:283)
	at com.zrp200.rkpd2.actors.mobs.Mob.onAttackComplete(Mob.java:630)
	at com.zrp200.rkpd2.sprites.CharSprite.onComplete(CharSprite.java:875)
	at com.zrp200.rkpd2.sprites.MobSprite.onComplete(MobSprite.java:46)
	at com.watabou.noosa.MovieClip.updateAnimation(MovieClip.java:72)
	at com.watabou.noosa.MovieClip.update(MovieClip.java:49)
	at com.zrp200.rkpd2.sprites.CharSprite.update(CharSprite.java:632)
	at com.zrp200.rkpd2.sprites.MobSprite.update(MobSprite.java:40)
	at com.watabou.noosa.Group.update(Group.java:64)
	at com.watabou.noosa.Group.update(Group.java:64)
	at com.watabou.noosa.Scene.update(Scene.java:63)
	at com.zrp200.rkpd2.scenes.PixelScene.update(PixelScene.java:173)
	at com.zrp200.rkpd2.scenes.GameScene.update(GameScene.java:667)
	at com.watabou.noosa.Game.update(Game.java:281)
	at com.watabou.noosa.Game.step(Game.java:245)
	at com.watabou.noosa.Game.render(Game.java:175)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)

***** END OF LOG *****

**Comment by zayats1** [comment]
A summoned rat cannot be cast to hero

**Comment by zayats1** [comment]
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: samsung
Device: m13
Model: SM-M135F
Manufacturer: samsung
Product: m13nnxx
SDK: 33
Release: 13

***** APP INFO 
Version: 1.5.1
Installed On: 2023-01-18 20:03:16
Updated On: 2023-01-29 18:29:02
Current Date: 2023-02-04 17:31:14

***** ERROR LOG 
java.lang.ClassCastException: com.zrp200.rkpd2.actors.hero.abilities.Ratmogrify$SummonedRat cannot be cast to com.zrp200.rkpd2.actors.hero.Hero
	at com.zrp200.rkpd2.items.weapon.Weapon$Enchantment.procChanceMultiplier(Weapon.java:408)
	at com.zrp200.rkpd2.items.weapon.enchantments.Explosive.tryProc(Explosive.java:22)
	at com.zrp200.rkpd2.items.weapon.enchantments.Explosive.proc(Explosive.java:26)
	at com.zrp200.rkpd2.actors.Char.attackProc(Char.java:681)
	at com.zrp200.rkpd2.actors.mobs.Mob.attackProc(Mob.java:736)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:431)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:287)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:283)
	at com.zrp200.rkpd2.actors.mobs.Mob.onAttackComplete(Mob.java:630)
	at com.zrp200.rkpd2.sprites.CharSprite.onComplete(CharSprite.java:875)
	at com.zrp200.rkpd2.sprites.MobSprite.onComplete(MobSprite.java:46)
	at com.watabou.noosa.MovieClip.updateAnimation(MovieClip.java:72)
	at com.watabou.noosa.MovieClip.update(MovieClip.java:49)
	at com.zrp200.rkpd2.sprites.CharSprite.update(CharSprite.java:632)
	at com.zrp200.rkpd2.sprites.MobSprite.update(MobSprite.java:40)
	at com.watabou.noosa.Group.update(Group.java:64)
	at com.watabou.noosa.Group.update(Group.java:64)
	at com.watabou.noosa.Scene.update(Scene.java:63)
	at com.zrp200.rkpd2.scenes.PixelScene.update(PixelScene.java:173)
	at com.zrp200.rkpd2.scenes.GameScene.update(GameScene.java:667)
	at com.watabou.noosa.Game.update(Game.java:281)
	at com.watabou.noosa.Game.step(Game.java:245)
	at com.watabou.noosa.Game.render(Game.java:175)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)



***** END OF LOG *****
