### ISSUE TITLE
Crash when travelling from floor 27 to floor 26

### ISSUE THREAD

**Issue by Luunae** [TrashboxBobylev/Rat-King-Adventure#9]
```
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: samsung
Device: b4q
Model: SM-F721U
Manufacturer: samsung
Product: b4qsqw
SDK: 33
Release: 13

***** APP INFO 
Version: 1.5.1
Installed On: 2023-04-22 23:28:10
Updated On: 2023-04-22 23:28:10
Current Date: 2023-04-26 16:12:18

***** ERROR LOG 
java.lang.RuntimeException: fatal error occured while moving between floors. Seed:591591264618 depth:26
    at com.zrp200.rkpd2.scenes.InterlevelScene.update(InterlevelScene.java:342)
    at com.watabou.noosa.Game.update(Game.java:281)
    at com.watabou.noosa.Game.step(Game.java:245)
    at com.watabou.noosa.Game.render(Game.java:175)
    at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.zrp200.rkpd2.levels.features.LevelTransition.cell()' on a null object reference
    at com.zrp200.rkpd2.scenes.InterlevelScene.ascend(InterlevelScene.java:458)
    at com.zrp200.rkpd2.scenes.InterlevelScene.access$500(InterlevelScene.java:50)
    at com.zrp200.rkpd2.scenes.InterlevelScene$4.run(InterlevelScene.java:264)



***** END OF LOG *****

```

**Comment by Luunae** [comment]
(Whoops, mobile ui weirdness shenanigans.)
